name: CI-Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build and check plugin
        uses: christopherfrieler/gradle-wrapper-action@v0.7.0
        with:
          arguments: |
            check build kotlinSourcesJar dokkaJavadocJar generatePomFileForPluginMavenPublication
          artifacts: |
            jars build/libs/android-release-gradle-plugin-*.jar
            pom build/publications/pluginMaven/pom-default.xml
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: ['build']
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Deploy to mavencentral
        uses: christopherfrieler/gradle-wrapper-action@v0.7.0
        env:
          ORG_GRADLE_PROJECT_signAllPublications: true
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_PASSWORD }}
        with:
          arguments: publishMavenPublicationToMavenCentralRepository
